# -*- coding: utf-8 -*-
"""DatasetScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFw0AJ5-gB7-ypGICF5erjTgrraJMT7x

# Dataset Scraping

## Imports
"""

# ! pip install python-dwca-reader

from dwca.read import DwCAReader
from dwca.darwincore.utils import qualname as qn
import requests
import shutil

"""## Globals"""

NUMBER_TO_SCRAPE = 10
DATASET_PATH = '/projectnb/sparkgrp/ml-herbarium-data/data.zip'
OUTPUT_PATH = '/projectnb/sparkgrp/ml-herbarium-data/scraped-data/'

"""## Mount Google Drive"""
# IGNORE UNLESS RUNNING ON GOOGLE COLAB
# from google.colab import drive
# drive.mount('/content/drive')

"""## Open DWCA File"""

dwca = DwCAReader(DATASET_PATH)

"""## Test DWCA"""

print(dwca.get_corerow_by_position(0))

"""## Save Rows to Variable"""

rows = dwca.rows

"""## Export Images to Google Drive"""

successIdxs = []
i = 0
while len(successIdxs) < NUMBER_TO_SCRAPE:
  url = rows[i].data['http://purl.org/dc/terms/references']
  if url != "":
    img_data = requests.get(url, stream = True)
    if img_data.status_code == 200:
      img_data.raw.decode_content = True
      fname = (str(i)+".jpg")
      with open(fname,'wb') as f:
        shutil.copyfileobj(img_data.raw, f)
      shutil.move(fname, OUTPUT_PATH)
      successIdxs.append(i)
      print('Image sucessfully Downloaded: ',fname)
  else:
      print('No image in row: '+str(i))
  i+=1

"""## Iterate Through Location Data & Save to .txt"""

list_countries = [] 

for x in successIdxs:
    #print(rows[x])
    #print(rows[x].data)
    #print("Location Data: "+rows[x].data["http://rs.tdwg.org/dwc/terms/higherGeography"])
    list_countries.append(str("Location Data: "+rows[x].data["http://rs.tdwg.org/dwc/terms/higherGeography"]).split(";")[1])


"""
rows = dwca.rows
#print(rows[0])
#print(rows[0].data)
str("Location Data: "+rows[0].data["http://rs.tdwg.org/dwc/terms/higherGeography"]).split(";")[1]
"""

print(list_countries)

with open('listcountries.txt', 'w') as filehandle:
    for listitem in list_countries:
        filehandle.write('%s\n' % listitem)
shutil.move('listcountries.txt', OUTPUT_PATH)

"""## Close the archive to free resources

"""

dwca.close()